### ISSUE TITLE
🆕 마우스 호버링 시 박스 생성되는 것 기능 고도화

### ISSUE THREAD

**Issue by myh9410** [NaverBunningDay-ShareHouse/MindReader#28]
## 기능 설명 (뭐 만들어?)
- 사용자가 마우스 호버링하면 호버링 한 곳의 텍스트 주변에 (현재는 1px solid black)의 테두리를 만들어주고 그 부분을 읽어줘야됨
- 현재 일부 href 링크 달려있는 태그들에서 동작이 어색하게 작동함.

**Comment by taeuk-gang** [comment]
현재 기능상은 정상 작동

- 다만, 탭간 중복 소리 작동 사항이 있으며, 고쳐야 할듯
