### ISSUE TITLE
🆕 API 테스트 작업할 공간 할당

### ISSUE THREAD

**Issue by taeuk-gang** [NaverBunningDay-ShareHouse/MindReader#9]
## 기능 설명 (뭐 만들어?)
CSS, OCR API 테스트할 작업 파일 지정
![브라보](https://user-images.githubusercontent.com/26294469/74402755-8ac5b700-4e68-11ea-86a0-2d0d67c25faf.gif)

**Comment by minhyeoky** [comment]
@taeuk-gang 생각해보니까 전후처리 빡세게 하고 싶으면 python 에서 하는게 편한데 백엔드가 없네

**Comment by minhyeoky** [comment]
@Cafemug @myh9410 api 테스트 된거잇으면 이슈좀 올려주세용

**Comment by minhyeoky** [comment]
++ 아 open 에 있네요
